# Hacer Base de datos de gobernadores y partidos

# AquÃ­ se eligen los folders donde se van a guardar los resultados
dir_output <- "4.Gobernar /18_Gobierno de Cuates/output/"
# Cuales años se incluyen en el estudio
añosincluidos <- seq(2020, 2010)

CLAVEEST <-
  c("AGS","BC","BCS","CAMP","CDMX","CHIH","CHIS","COAH","COL","DGO","GRO",
    "GTO","HGO","JAL","MEX","MICH","MOR","NAY","NL","OAX","PUE","Q_ROO","QRO",
    "SIN","SLP","SON","TAB","TAMPS","TLAX","VER","YUC","ZAC"
  )

años_edos_gob <- data.frame("año" = rep(añosincluidos, length(CLAVEEST)), "estado" =rep(CLAVEEST, length(añosincluidos))) %>% 
  mutate(clave_gob = case_when(
    estado == "AGS"   & año >= 2011 & año < 2014 ~ "2Lozano1",
    estado == "AGS"   & año >= 2014 & año < 2017 ~ "3Lozano2",
    estado == "AGS"   & año >= 2017 & año < 2019 ~ "4Orozco1",
    estado == "AGS"   & año >= 2019              ~ "5Orozco2",
    estado == "BC"    & año >= 2011 & año < 2014 ~ "2Osuna2",
    estado == "BC"    & año >= 2014 & año < 2017 ~ "3Vega1" ,
    estado == "BC"    & año >= 2017 & año < 2020 ~ "4Vega2" ,
    estado == "BC"    & año >= 2020              ~ "5Quitar1",
    estado == "BCS"   & año >= 2011 & año < 2014 ~ "2Covarrubias1" ,
    estado == "BCS"   & año >= 2014 & año < 2016 ~ "3Covarrubias2" ,
    estado == "BCS"   & año >= 2016 & año < 2019 ~ "4Mendoza1"     ,
    estado == "BCS"   & año >= 2019              ~ "5Mendoza2"     ,
    estado == "CAMP"  & año <  2013              ~ "1Ortega1",
    estado == "CAMP"  & año >= 2013 & año < 2016 ~ "2Ortega2"       ,
    estado == "CAMP"  & año >= 2016 & año < 2019 ~ "3Moreno_C1"     ,
    estado == "CAMP"  & año >= 2019              ~ "4Moreno_C2_Aysa",
    estado == "CDMX"  & año <  2013              ~ "1Ebrard2",
    estado == "CDMX"  & año >= 2013 & año < 2016 ~ "2Mancera1"  ,
    estado == "CDMX"  & año >= 2016 & año < 2019 ~ "3Mancera2"  ,
    estado == "CDMX"  & año >= 2019              ~ "4Sheinbaum1",
    estado == "CHIH"  & año >= 2011 & año < 2014 ~ "2Duarte_C1",
    estado == "CHIH"  & año >= 2014 & año < 2017 ~ "3Duarte_C2",
    estado == "CHIH"  & año >= 2017 & año < 2019 ~ "4Corral1"  ,
    estado == "CHIH"  & año >= 2019              ~ "5Corral2"  ,
    estado == "CHIS"  & año <  2013              ~ "1Sabines2",
    estado == "CHIS"  & año >= 2013 & año < 2016 ~ "2Velasco1",
    estado == "CHIS"  & año >= 2016 & año < 2019 ~ "3Velasco2",
    estado == "CHIS"  & año >= 2019              ~ "4Escandon1",
    estado == "COAH"  & año <  2012              ~ "1Torres2",
    estado == "COAH"  & año >= 2012 & año < 2015 ~ "2Moreira1"  ,
    estado == "COAH"  & año >= 2015 & año < 2018 ~ "3Moreira2"  ,
    estado == "COAH"  & año >= 2018              ~ "4Riquelme1" ,
    estado == "COL"   & año <  2013              ~ "1Anguiano1",
    estado == "COL"   & año >= 2013 & año < 2016 ~ "2Anguiano2_Perez",
    estado == "COL"   & año >= 2016 & año < 2019 ~ "3Peralta1",
    estado == "COL"   & año >= 2019              ~ "4Peralta2",
    estado == "DGO"   & año >= 2011 & año < 2014 ~ "2Herrera_Dg1",
    estado == "DGO"   & año >= 2014 & año < 2017 ~ "3Herrera_Dg2",
    estado == "DGO"   & año >= 2017 & año < 2019 ~ "4Rosas1",
    estado == "DGO"   & año >= 2019              ~ "5Rosas2",
    estado == "GRO"   & año >= 2011 & año < 2014 ~ "2Aguirre_Varios1",
    estado == "GRO"   & año >= 2014 & año < 2016 ~ "3Aguirre_Varios2",
    estado == "GRO"   & año >= 2016 & año < 2019 ~ "4Astudillo1",
    estado == "GRO"   & año >= 2019              ~ "5Astudillo2",
    estado == "GTO"   & año <  2013              ~ "1Lopez2",
    estado == "GTO"   & año >= 2013 & año < 2016 ~ "2Marquez1",
    estado == "GTO"   & año >= 2016 & año < 2019 ~ "3Marquez2",
    estado == "GTO"   & año >= 2019              ~ "4Sinhue1",
    estado == "HGO"   & año >= 2011 & año < 2014 ~ "2Olvera1",
    estado == "HGO"   & año >= 2014 & año < 2017 ~ "3Olvera2",
    estado == "HGO"   & año >= 2017 & año < 2019 ~ "4Fayad1",
    estado == "HGO"   & año >= 2019              ~ "5Fayad2",
    estado == "JAL"   & año <  2013              ~ "1Gonzalez_J2",
    estado == "JAL"   & año >= 2013 & año < 2016 ~ "2Sandoval_J1",
    estado == "JAL"   & año >= 2016 & año < 2019 ~ "3Sandoval_J2",
    estado == "JAL"   & año >= 2019 & año < 2012 ~ "4Alfaro1",
    estado == "JAL"   & año <  2012              ~ "1Gonzalez_J2",
    estado == "MEX"   & año >= 2012 & año < 2015 ~ "2Avila1",
    estado == "MEX"   & año >= 2015 & año < 2018 ~ "3Avila2",
    estado == "MEX"   & año >= 2018              ~ "4DelMazo1",
    estado == "MICH"  & año <  2012              ~ "1Godoy2",
    estado == "MICH"  & año >= 2012 & año < 2014 ~ "2Vallejo_Jara1",
    estado == "MICH"  & año >= 2014 & año < 2016 ~ "3Vallejo_Jara2",
    estado == "MICH"  & año >= 2016 & año < 2019 ~ "4Aureoles1",
    estado == "MICH"  & año >= 2019              ~ "5Aureoles2",
    estado == "MOR"   & año <  2013              ~ "1Adame2",
    estado == "MOR"   & año >= 2013 & año < 2016 ~ "2Ramirez1",
    estado == "MOR"   & año >= 2016 & año < 2019 ~ "3Ramirez2",
    estado == "MOR"   & año >= 2019              ~ "4Blanco1",
    estado == "NAY"   & año <  2012              ~ "1Gonzalez_Ny",
    estado == "NAY"   & año >= 2012 & año < 2015 ~ "2Sandoval_Ny1",
    estado == "NAY"   & año >= 2015 & año < 2018 ~ "3Sandoval_Ny2",
    estado == "NAY"   & año >= 2018              ~ "4Echeverria1",
    estado == "NL"    & año <  2013              ~ "1Medina1",
    estado == "NL"    & año >= 2013 & año < 2016 ~ "2Medina2" ,
    estado == "NL"    & año >= 2016 & año < 2019 ~ "3Rodriguez1" ,
    estado == "NL"    & año >= 2019              ~ "4Rodriguez2_Gonzalez" ,
    estado == "OAX"   & año >= 2011 & año < 2014 ~ "2Cue1",
    estado == "OAX"   & año >= 2014 & año < 2017 ~ "3Cue2",
    estado == "OAX"   & año >= 2017 & año < 2019 ~ "4Murat1",
    estado == "OAX"   & año >= 2019              ~ "5Murat2",
    estado == "PUE"   & año >= 2011 & año < 2014 ~ "2Moreno1",
    estado == "PUE"   & año >= 2014 & año < 2017 ~ "3Moreno2",
    estado == "PUE"   & año >= 2017 & año < 2019 ~ "4Gali1",
    estado == "PUE"   & año >= 2019              ~ "5Barbosa1",
    estado == "Q_ROO" & año >= 2011 & año < 2014 ~ "2Borge1",
    estado == "Q_ROO" & año >= 2014 & año < 2017 ~ "3Borge2",
    estado == "Q_ROO" & año >= 2017 & año < 2019 ~ "4Joaquin1",
    estado == "Q_ROO" & año >= 2019              ~ "5Joaquin2",
    estado == "QRO"   & año <  2013              ~ "1Calzada1",
    estado == "QRO"   & año >= 2013 & año < 2016 ~ "2Calzada2_Portillo",
    estado == "QRO"   & año >= 2016 & año < 2019 ~ "3Dominguez1",
    estado == "QRO"   & año >= 2019              ~ "4Dominguez2",
    estado == "SIN"   & año >= 2011 & año < 2014 ~ "2Lopez1" ,
    estado == "SIN"   & año >= 2014 & año < 2017 ~ "3Lopez2" ,
    estado == "SIN"   & año >= 2017 & año < 2019 ~ "4Ordaz1" ,
    estado == "SIN"   & año >= 2019              ~ "5Ordaz2" ,
    estado == "SLP"   & año <  2013              ~ "1Toranzo1",
    estado == "SLP"   & año >= 2013 & año < 2016 ~ "2Toranzo2" ,
    estado == "SLP"   & año >= 2016 & año < 2019 ~ "3Carreras1" ,
    estado == "SLP"   & año >= 2019              ~ "4Carreras2" ,
    estado == "SON"   & año <  2013              ~ "1Padres1",
    estado == "SON"   & año >= 2013 & año < 2016 ~ "2Padres2",
    estado == "SON"   & año >= 2016 & año < 2019 ~ "3Pavlovich1",
    estado == "SON"   & año >= 2019              ~ "4Pavlovich2",
    estado == "TAB"   & año <  2013              ~ "1Granier2",
    estado == "TAB"   & año >= 2013 & año < 2016 ~ "2Nuñez1",
    estado == "TAB"   & año >= 2016 & año < 2019 ~ "3Nuñez2",
    estado == "TAB"   & año >= 2019              ~ "4Lopez1",
    estado == "TAMPS" & año >= 2011 & año < 2014 ~ "2Torre1" ,
    estado == "TAMPS" & año >= 2014 & año < 2017 ~ "3Torre2" ,
    estado == "TAMPS" & año >= 2017 & año < 2019 ~ "4Garcia_Tp1" ,
    estado == "TAMPS" & año >= 2019              ~ "5Garcia_Tp2" ,
    estado == "TLAX"  & año >= 2011 & año < 2014 ~ "2Gonzalez_Tl1",
    estado == "TLAX"  & año >= 2014 & año < 2017 ~ "3Gonzalez_Tl2",
    estado == "TLAX"  & año >= 2017 & año < 2019 ~ "4Mena1",
    estado == "TLAX"  & año >= 2019              ~ "5Mena2",
    estado == "VER"   & año >= 2011 & año < 2014 ~ "2Duarte_V1",
    estado == "VER"   & año >= 2014 & año < 2017 ~ "3Duarte_V2",
    estado == "VER"   & año >= 2017 & año < 2019 ~ "4Yunes1",
    estado == "VER"   & año >= 2019              ~ "5Garcia_V1",
    estado == "YUC"   & año <  2013              ~ "1Ortega2",
    estado == "YUC"   & año >= 2013 & año < 2016 ~ "2Zapata1" ,
    estado == "YUC"   & año >= 2016 & año < 2019 ~ "3Zapata2" ,
    estado == "YUC"   & año >= 2019              ~ "4Vila1" ,
    estado == "ZAC"   & año >= 2011 & año < 2014 ~ "2Alonso1",
    estado == "ZAC"   & año >= 2014 & año < 2017 ~ "3Alonso2",
    estado == "ZAC"   & año >= 2017 & año < 2019 ~ "4Tello1",
    estado == "ZAC"   & año >= 2019              ~ "5Tello2",
    T ~ "1Quitar4",
  )) %>% 
  mutate(periodo_absoluto = as.numeric(stri_extract_first(clave_gob, regex = "[:digit:]")),
         periodo_de_gobernador = as.numeric(stri_extract_last(clave_gob, regex = "[:digit:]")),
         gobernador = stri_extract_first(clave_gob, regex = "[[:alpha:]_]+"),
  ) %>% 
  left_join(
    tribble(
      ~estado ,~periodo_absoluto, ~gobernador     , ~partido,
      "AGS"   ,1                , "Quitar"        , "PAN",
      "AGS"   ,2                , "Lozano"        , "PRI",
      "AGS"   ,3                , "Lozano"        , "PRI",
      "AGS"   ,4                , "Orozco"        , "PAN",
      "AGS"   ,5                , "Orozco"        , "PAN",
      "BC"    ,1                , "Quitar"        , "PAN",
      "BC"    ,2                , "Osuna"         , "PAN",
      "BC"    ,3                , "Vega"          , "PAN",
      "BC"    ,4                , "Vega"          , "PAN",
      "BC"    ,5                , "Quitar"        , "PAN",
      "BCS"   ,1                , "Quitar"        , "PRD",
      "BCS"   ,2                , "Covarrubias"   , "PAN",
      "BCS"   ,3                , "Covarrubias"   , "PAN",
      "BCS"   ,4                , "Mendoza"       , "PAN",
      "BCS"   ,5                , "Mendoza"       , "PAN",
      "CAMP"  ,1                , "Ortega"        , "PRI",
      "CAMP"  ,2                , "Ortega"        , "PRI",
      "CAMP"  ,3                , "Moreno_C"      , "PRI",
      "CAMP"  ,4                , "Moreno_C"      , "PRI",
      "CDMX"  ,1                , "Ebrard"        , "PRD",
      "CDMX"  ,2                , "Mancera"       , "PRD",
      "CDMX"  ,3                , "Mancera"       , "PRD",
      "CDMX"  ,4                , "Sheinbaum"     , "MORENA",
      "CHIH"  ,1                , "Quitar"        , "PRI",
      "CHIH"  ,2                , "Duarte_C"      , "PRI",
      "CHIH"  ,3                , "Duarte_C"      , "PRI",
      "CHIH"  ,4                , "Corral"        , "PAN",
      "CHIH"  ,5                , "Corral"        , "PAN",
      "CHIS"  ,1                , "Sabines"       , "PRD",
      "CHIS"  ,2                , "Velasco"       , "PVEM",
      "CHIS"  ,3                , "Velasco"       , "PVEM",
      "CHIS"  ,4                , "Escandon"      , "MORENA",
      "COAH"  ,1                , "Torres"        , "PRI",
      "COAH"  ,2                , "Moreira"       , "PRI",
      "COAH"  ,3                , "Moreira"       , "PRI",
      "COAH"  ,4                , "Riquelme"      , "PRI",
      "COL"   ,1                , "Anguiano"      , "PRI",
      "COL"   ,2                , "Anguiano"      , "PRI",
      "COL"   ,3                , "Peralta"       , "PRI",
      "COL"   ,4                , "Peralta"       , "PRI",
      "DGO"   ,1                , "Quitar"        , "PRI",
      "DGO"   ,2                , "Herrera_Dg"    , "PRI",
      "DGO"   ,3                , "Herrera_Dg"    , "PRI",
      "DGO"   ,4                , "Rosas"         , "PAN",
      "DGO"   ,5                , "Rosas"         , "PAN",
      "GRO"   ,1                , "Quitar"        , "PRD",
      "GRO"   ,2                , "Aguirre_Varios", "PRD",
      "GRO"   ,3                , "Aguirre_Varios", "PRD",
      "GRO"   ,4                , "Astudillo"     , "PRI",
      "GRO"   ,5                , "Astudillo"     , "PRI",
      "GTO"   ,1                , "Lopez"         , "PAN",
      "GTO"   ,2                , "Marquez"       , "PAN",
      "GTO"   ,3                , "Marquez"       , "PAN",
      "GTO"   ,4                , "Sinhue"        , "PAN",
      "HGO"   ,1                , "Quitar"        , "PRI",
      "HGO"   ,2                , "Olvera"        , "PRI",
      "HGO"   ,3                , "Olvera"        , "PRI",
      "HGO"   ,4                , "Fayad"         , "PRI",
      "HGO"   ,5                , "Fayad"         , "PRI",
      "JAL"   ,1                , "Gonzalez_J"    , "PAN",
      "JAL"   ,1                , "Quitar"        , "MC",
      "JAL"   ,2                , "Sandoval_J"    , "PRI",
      "JAL"   ,3                , "Sandoval_J"    , "PRI",
      "MEX"   ,1                , "Quitar"        , "PRI",
      "MEX"   ,2                , "Avila"         , "PRI",
      "MEX"   ,3                , "Avila"         , "PRI",
      "MEX"   ,4                , "DelMazo"       , "PRI",
      "MICH"  ,1                , "Godoy"         , "PRD",
      "MICH"  ,2                , "Vallejo_Jara"  , "PRI",
      "MICH"  ,3                , "Vallejo_Jara"  , "PRI",
      "MICH"  ,4                , "Aureoles"      , "PRD",
      "MICH"  ,5                , "Aureoles"      , "PRD",
      "MOR"   ,1                , "Adame"         , "PAN",
      "MOR"   ,2                , "Ramirez"       , "PRD",
      "MOR"   ,3                , "Ramirez"       , "PRD",
      "MOR"   ,4                , "Blanco"        , "PES",
      "NAY"   ,0                , "Quitar"        , "PAN",
      "NAY"   ,1                , "Gonzalez_Ny"   , "PRI",
      "NAY"   ,2                , "Sandoval_Ny"   , "PRI",
      "NAY"   ,3                , "Sandoval_Ny"   , "PRI",
      "NAY"   ,4                , "Echeverria"    , "PAN",
      "NL"    ,1                , "Medina"        , "PRI",
      "NL"    ,2                , "Medina"        , "PRI",
      "NL"    ,3                , "Rodriguez"     , "Independiente",
      "NL"    ,4                , "Rodriguez"     , "Independiente",
      "OAX"   ,1                , "Quitar"        , "PRI",
      "OAX"   ,2                , "Cue"           , "MC",
      "OAX"   ,3                , "Cue"           , "MC",
      "OAX"   ,4                , "Murat"         , "PRI",
      "OAX"   ,5                , "Murat"         , "PRI",
      "PUE"   ,1                , "Quitar"        , "PRI",
      "PUE"   ,2                , "Moreno"        , "PAN",
      "PUE"   ,3                , "Moreno"        , "PAN",
      "PUE"   ,4                , "Gali"          , "PAN",
      "PUE"   ,5                , "Barbosa"       , "MORENA",
      "Q_ROO" ,1                , "Quitar"        , "PRI",
      "Q_ROO" ,2                , "Borge"         , "PRI",
      "Q_ROO" ,3                , "Borge"         , "PRI",
      "Q_ROO" ,4                , "Joaquin"       , "PAN",
      "Q_ROO" ,5                , "Joaquin"       , "PAN",
      "QRO"   ,0                , "Quitar"        , "PAN",
      "QRO"   ,1                , "Calzada"       , "PRI",
      "QRO"   ,2                , "Calzada"       , "PRI",
      "QRO"   ,3                , "Dominguez"     , "PAN",
      "QRO"   ,4                , "Dominguez"     , "PAN",
      "SIN"   ,1                , "Quitar"        , "PRI",
      "SIN"   ,2                , "Lopez"         , "PAN",
      "SIN"   ,3                , "Lopez"         , "PAN",
      "SIN"   ,4                , "Ordaz"         , "PRI",
      "SIN"   ,5                , "Ordaz"         , "PRI",
      "SLP"   ,0                , "Quitar"        , "PAN",
      "SLP"   ,1                , "Toranzo"       , "PRI",
      "SLP"   ,2                , "Toranzo"       , "PRI",
      "SLP"   ,3                , "Carreras"      , "PRI",
      "SLP"   ,4                , "Carreras"      , "PRI",
      "SON"   ,0                , "Quitar"        , "PRI",
      "SON"   ,1                , "Padres"        , "PAN",
      "SON"   ,2                , "Padres"        , "PAN",
      "SON"   ,3                , "Pavlovich"     , "PRI",
      "SON"   ,4                , "Pavlovich"     , "PRI",
      "TAB"   ,1                , "Granier"       , "PRI",
      "TAB"   ,2                , "Nuñez"         , "PRD",
      "TAB"   ,3                , "Nuñez"         , "PRD",
      "TAB"   ,4                , "Lopez"         , "MORENA",
      "TAMPS" ,1                , "Quitar"        , "PRI",
      "TAMPS" ,2                , "Torre"         , "PRI",
      "TAMPS" ,3                , "Torre"         , "PRI",
      "TAMPS" ,4                , "Garcia_Tp"     , "PAN",
      "TAMPS" ,5                , "Garcia_Tp"     , "PAN",
      "TLAX"  ,1                , "Quitar"        , "PAN",
      "TLAX"  ,2                , "Gonzalez_Tl"   , "PRI",
      "TLAX"  ,3                , "Gonzalez_Tl"   , "PRI",
      "TLAX"  ,4                , "Mena"          , "PRI",
      "TLAX"  ,5                , "Mena"          , "PRI",
      "VER"   ,1                , "Quitar"        , "PRI",
      "VER"   ,2                , "Duarte_V"      , "PRI",
      "VER"   ,3                , "Duarte_V"      , "PRI",
      "VER"   ,4                , "Yunes"         , "PAN",
      "VER"   ,5                , "Garcia_V"      , "MORENA",
      "YUC"   ,1                , "Ortega"        , "PRI",
      "YUC"   ,2                , "Zapata"        , "PRI",
      "YUC"   ,3                , "Zapata"        , "PRI",
      "YUC"   ,4                , "Vila"          , "PAN",
      "ZAC"   ,1                , "Quitar"        , "PRD",
      "ZAC"   ,2                , "Alonso"        , "PRI",
      "ZAC"   ,3                , "Alonso"        , "PRI",
      "ZAC"   ,4                , "Tello"         , "PRI",
      "ZAC"   ,5                , "Tello"         , "PRI",
    )
  ) %>% 
  arrange(estado, año)

openxlsx::write.xlsx(años_edos_gob, paste0(dir_output, "gobiernos.xlsx"))
